New modal
backstage-ui/backstage-modal pull request #1
Opened 2017-01-09 21:10 UTC by MayconDionisio

2017-01-11 12:22 UTC, raphamorim commented
Hi @MayconDionisio, can you adjust lint tests?

2017-01-11 12:38 UTC, MayconDionisio commented
Sorry for that @raphamorim, i will adjust the lint tests and other things.

2017-01-19 12:37 UTC, ricobl requested changes
Apart from the font, looks good to me! Thanks!

2017-01-19 12:37 UTC, ricobl commented on dist/modal.css.js
> +    fontFamily: '"Open Sans" "sans-serif"',
The comma is missing here...

2017-01-19 12:42 UTC, raphamorim commented on dist/modal.css.js
> +    fontFamily: '"Open Sans" "sans-serif"',
Check this refator: `fontFamily: ['sans-serif', 'Open Sans'],`

2017-01-19 13:05 UTC, MayconDionisio commented on dist/modal.css.js
> +    fontFamily: '"Open Sans" "sans-serif"',
Ok, i'll do that. Thanks!

2017-01-30 18:40 UTC, merged